### ISSUE TITLE
sudo rmmod r8188eu.ko

### ISSUE THREAD

**Issue by mbino94** [Munazirul/rtl8188eus#1]
when i run the sudo rmmod command
i get this error

`rmmod: ERROR: Module r8188eu is not currently loaded`

**Comment by Munazirul** [comment]
I was facing the same issue before, then it was  fixed..
Then there can be two solutions to  this problem:
1. reboot
or
2. remove the rtl8188eus folder and re-clone the repository again and repeat all the steps. (make sure you have inserted your adapter during the process)

> when i run the sudo rmmod command i get this error
> 
> `rmmod: ERROR: Module r8188eu is not currently loaded`

**Comment by Munazirul** [comment]
Following these steps should solve the issue.

1. `sudo apt update`
2. `sudo apt install dkms bc`
3. `git clone https://github.com/Munazirul/rtl8188eus`
4. `cd rtl8188eus`
5. `echo "blacklist r8188eu.ko" >> "/etc/modprobe.d/realtek.conf"`
6. `echo "blacklist 8188eu.ko" >> "/etc/modprobe.d/realtek.conf"`
7. `sudo make`
8. `sudo make install`
9. `sudo reboot` (must)
10. `sudo modprobe 8188eu` (Only if the wifi networks are not shown on your machine)

**Comment by mbino94** [comment]
> Following these steps should solve the issue.
> 
> 1. `sudo apt update`
> 2. `sudo apt install dkms bc`
> 3. `git clone https://github.com/Munazirul/rtl8188eus`
> 4. `cd rtl8188eus`
> 5. `echo "blacklist r8188eu.ko" >> "/etc/modprobe.d/realtek.conf"`
> 6. `echo "blacklist 8188eu.ko" >> "/etc/modprobe.d/realtek.conf"`
> 7. `sudo make`
> 8. `sudo make install`
> 9. `sudo reboot` (must)
> 10. `sudo modprobe 8188eu` (Only if the wifi networks are not shown on your machine)

OMG!!! YOU'RE THE MAN!!
i repeated that shit for a month and nothing changed!
but now it working perfect!
you deserve a medal

**Comment by Sanchitkanwar31** [comment]
> 8\. sudo make install

i was facing the following error:
install: cannot stat '8188eu.ko': No such file or directory
