### ISSUE TITLE
Not working on Raspberry Pi 3/Bullseye

### ISSUE THREAD

**Issue by sahver** [Munazirul/rtl8188eus#2]
Not working on Raspberry Pi 3/Bullseye.

Compiles fine, reboot, but unable to scan networks. Also tried to load the module as suggested, but no change.

`sudo iw dev wlan0 scan`

results in

`command failed: No such device (-19)`

**Comment by Munazirul** [comment]
> Not working on Raspberry Pi 3/Bullseye.
> 
> Compiles fine, reboot, but unable to scan networks. Also tried to load the module as suggested, but no change.
> 
> `sudo iw dev wlan0 scan`
> 
> results in
> 
> `command failed: No such device (-19)`

Hi,
First check your wireless adapter interface using the command
`ifconfig`
or
`iwconfig`
and then replace wlan0 with the correct interface.
This could be the reason you got this error. Let me know If still error persists.

**Comment by sahver** [comment]
Both of the adapters wlan0 (TP-link wn772n v2) and wlan1 (inbuilt) were present in the `ifconfig` listing.

I managed to fix the issue by additionally blacklisting `8188eu`

`echo "blacklist r8188eu" >> "/etc/modprobe.d/realtek.conf"`
